In [1]:
import pandas as pd
import numpy as np

In [2]:
df2012 = pd.read_csv('../data/2012_Census_-_Dwelling_Unit_Status__Neighbourhood_.csv')
df2014 = pd.read_csv('../data/2014_Census_-_Dwelling_Unit_Status__Neighbourhood_.csv')
df2016 = pd.read_csv('../data/2016_Census_-_Population_By_Dwelling_Unit_Status__Neighbourhood_.csv')

In [3]:
df2012['UNOCCUPIED'] = df2012['UNOCCUPIED'] + df2012['VACANT_LOT']
df2012['OCCUPIED'] = df2012['OCCUPIED'] + df2012['UNDER_CONSTRUCTION']

In [4]:
del df2012['VACANT_LOT']
del df2012['UNDER_CONSTRUCTION']

In [5]:
new_columns = df2016.columns
new_columns

Index(['﻿Ward', 'Neighbourhood Number', 'Neighbourhood Name', 'Occupied',
       'Unoccupied', 'No Longer In Use', 'No Response'],
      dtype='object')

In [6]:
# The column names is changed in 2016, need some unification
df2012.columns = new_columns
df2014.columns = new_columns

In [7]:
df2012.columns == df2016.columns

array([ True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [8]:
df2012.columns == df2014.columns

array([ True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [9]:
def build(df, year):
    df_minus = pd.DataFrame(dtype='int64')
    for idx, row in df.iterrows():
        for i in range(1, 5):
            for j in range(1, 4):
                row['Quarter'] = int(i)
                row['Month'] = int(3*(i-1)+j)
                row['Year'] = int(year)
                df_minus = df_minus.append(row)
    return df_minus

In [10]:
df2011 = build(df2012, 2011)
df2012 = build(df2012, 2012)
df2013 = build(df2014, 2013)
df2014 = build(df2014, 2014)
df2015 = build(df2016, 2015)
df2016 = build(df2016, 2016)

In [11]:
final_df = pd.DataFrame()
final_df = final_df.append(df2011).append(df2012).append(df2013).append(df2014).append(df2015).append(df2016)
del final_df['No Response']

In [12]:
for i in final_df.columns:
    try:
        final_df[i] = final_df[i].astype('int64')
        print(i, 'is an int64 column')
    except:
        print(i, 'is not an int64 column')

Month is an int64 column
Neighbourhood Name is not an int64 column
Neighbourhood Number is an int64 column
No Longer In Use is an int64 column
Occupied is an int64 column
Quarter is an int64 column
Unoccupied is an int64 column
Year is an int64 column
﻿Ward is not an int64 column

In [13]:
final_df

,Month,Neighbourhood Name,Neighbourhood Number,No Longer In Use,Occupied,Quarter,Unoccupied,Year,﻿Ward
0,1,ALBERTA PARK INDUSTRIAL,4010,0,0,1,0,2011,Ward 1
0,2,ALBERTA PARK INDUSTRIAL,4010,0,0,1,0,2011,Ward 1
0,3,ALBERTA PARK INDUSTRIAL,4010,0,0,1,0,2011,Ward 1
0,4,ALBERTA PARK INDUSTRIAL,4010,0,0,2,0,2011,Ward 1
0,5,ALBERTA PARK INDUSTRIAL,4010,0,0,2,0,2011,Ward 1
0,6,ALBERTA PARK INDUSTRIAL,4010,0,0,2,0,2011,Ward 1
0,7,ALBERTA PARK INDUSTRIAL,4010,0,0,3,0,2011,Ward 1
0,8,ALBERTA PARK INDUSTRIAL,4010,0,0,3,0,2011,Ward 1
0,9,ALBERTA PARK INDUSTRIAL,4010,0,0,3,0,2011,Ward 1
0,10,ALBERTA PARK INDUSTRIAL,4010,0,0,4,0,2011,Ward 1
0,11,ALBERTA PARK INDUSTRIAL,4010,0,0,4,0,2011,Ward 1
0,12,ALBERTA PARK INDUSTRIAL,4010,0,0,4,0,2011,Ward 1
1,1,ALDERGROVE,4020,32,1946,1,39,2011,Ward 1
1,2,ALDERGROVE,4020,32,1946,1,39,2011,Ward 1
1,3,ALDERGROVE,4020,32,1946,1,39,2011,Ward 1
1,4,ALDERGROVE,4020,32,1946,2,39,2011,Ward 1
1,5,ALDERGROVE,4020,32,1946,2,39,2011,Ward 1
1,6,ALDERGROVE,4020,32,1946,2,39,2011,Ward 1
1,7,ALDERGROVE,4020,32,1946,3,39,2011,Ward 1
1,8,ALDERGROVE,4020,32,1946,3,39,2011,Ward 1
1,9,ALDERGROVE,4020,32,1946,3,39,2011,Ward 1
1,10,ALDERGROVE,4020,32,1946,4,39,2011,Ward 1
1,11,ALDERGROVE,4020,32,1946,4,39,2011,Ward 1
1,12,ALDERGROVE,4020,32,1946,4,39,2011,Ward 1
2,1,ANTHONY HENDAY,4011,0,0,1,0,2011,Ward 1
2,2,ANTHONY HENDAY,4011,0,0,1,0,2011,Ward 1
2,3,ANTHONY HENDAY,4011,0,0,1,0,2011,Ward 1
2,4,ANTHONY HENDAY,4011,0,0,2,0,2011,Ward 1
2,5,ANTHONY HENDAY,4011,0,0,2,0,2011,Ward 1
2,6,ANTHONY HENDAY,4011,0,0,2,0,2011,Ward 1
...,...,...,...,...,...,...,...,...,...
385,7,OZERNA,2600,0,1355,3,40,2016,WARD 3
385,8,OZERNA,2600,0,1355,3,40,2016,WARD 3
385,9,OZERNA,2600,0,1355,3,40,2016,WARD 3
385,10,OZERNA,2600,0,1355,4,40,2016,WARD 3
385,11,OZERNA,2600,0,1355,4,40,2016,WARD 3
385,12,OZERNA,2600,0,1355,4,40,2016,WARD 3
386,1,TERRA LOSA,4540,1,1302,1,149,2016,WARD 1
386,2,TERRA LOSA,4540,1,1302,1,149,2016,WARD 1
386,3,TERRA LOSA,4540,1,1302,1,149,2016,WARD 1
386,4,TERRA LOSA,4540,1,1302,2,149,2016,WARD 1
386,5,TERRA LOSA,4540,1,1302,2,149,2016,WARD 1
386,6,TERRA LOSA,4540,1,1302,2,149,2016,WARD 1
386,7,TERRA LOSA,4540,1,1302,3,149,2016,WARD 1
386,8,TERRA LOSA,4540,1,1302,3,149,2016,WARD 1
386,9,TERRA LOSA,4540,1,1302,3,149,2016,WARD 1
386,10,TERRA LOSA,4540,1,1302,4,149,2016,WARD 1
386,11,TERRA LOSA,4540,1,1302,4,149,2016,WARD 1
386,12,TERRA LOSA,4540,1,1302,4,149,2016,WARD 1
387,1,RIVER VALLEY HERMITAGE,2630,0,0,1,0,2016,WARD 4
387,2,RIVER VALLEY HERMITAGE,2630,0,0,1,0,2016,WARD 4
387,3,RIVER VALLEY HERMITAGE,2630,0,0,1,0,2016,WARD 4
387,4,RIVER VALLEY HERMITAGE,2630,0,0,2,0,2016,WARD 4
387,5,RIVER VALLEY HERMITAGE,2630,0,0,2,0,2016,WARD 4
387,6,RIVER VALLEY HERMITAGE,2630,0,0,2,0,2016,WARD 4
387,7,RIVER VALLEY HERMITAGE,2630,0,0,3,0,2016,WARD 4
387,8,RIVER VALLEY HERMITAGE,2630,0,0,3,0,2016,WARD 4
387,9,RIVER VALLEY HERMITAGE,2630,0,0,3,0,2016,WARD 4
387,10,RIVER VALLEY HERMITAGE,2630,0,0,4,0,2016,WARD 4
387,11,RIVER VALLEY HERMITAGE,2630,0,0,4,0,2016,WARD 4
387,12,RIVER VALLEY HERMITAGE,2630,0,0,4,0,2016,WARD 4

In [14]:
final_df.to_csv('../merged_data/Dwelling_Unit_Status.csv')